# Generated by Django 5.0.6 on 2024-07-01 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('duration', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=500)),
                ('status', models.BooleanField(default=True)),
                ('experience', models.CharField(max_length=100)),
                ('courses', models.ManyToManyField(to='app.courses')),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=13)),
                ('parents_phone_number', models.CharField(max_length=13)),
                ('telegram_link', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('courses', models.ManyToManyField(to='app.courses')),
                ('teachers', models.ManyToManyField(to='app.teachers')),
            ],
        ),
    ]
